In [10]:
%load_ext autoreload
%load_ext tensorboard
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [9]:
# System imports
import os
import sys
import yaml

# External imports
import scipy as sp
import numpy as np
import pandas as pd
import torch
from pytorch_lightning import Trainer
from pytorch_lightning.loggers import TensorBoardLogger

sys.path.append('..')
device = "cuda" if torch.cuda.is_available() else "cpu"
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
import nersc_tensorboard_helper

In [11]:
from LightningModules.GNN.Models.ecgnn import ECGNN

In [15]:
with open("example_gnn.yaml") as f:
        hparams = yaml.load(f, Loader=yaml.FullLoader)

In [16]:
model = ECGNN(hparams)
logger = TensorBoardLogger("tb_ecgnn_logs",name = "ecgnn")
trainer = Trainer(gpus=1,max_epochs=20,logger = logger)
torch.autograd.set_detect_anomaly(True)
trainer.fit(model)

GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Set SLURM handle signals.

  | Name          | Type        | Params
----------------------------------------------
0 | input_network | Sequential  | 288   
1 | node_network  | NodeNetwork | 9.8 K 
2 | edge_network  | EdgeNetwork | 10.9 K
----------------------------------------------
21.0 K    Trainable params
0         Non-trainable params
21.0 K    Total params


Epoch 0:  25%|██▌       | 10/40 [00:13<00:40,  1.35s/it, loss=0.948, v_num=161]2
tensor([2470], device='cuda:0')
tensor(2470, device='cuda:0')
10237 14728
tensor(10236, device='cuda:0')
Epoch 0:  50%|█████     | 20/40 [00:26<00:26,  1.32s/it, loss=0.946, v_num=161]
Validating: 0it [00:00, ?it/s]
Epoch 1:  50%|█████     | 20/40 [00:26<00:26,  1.32s/it, loss=0.904, v_num=161]
Validating: 0it [00:00, ?it/s]
Epoch 1:  60%|██████    | 24/40 [00:28<00:18,  1.18s/it, loss=0.904, v_num=161]2
tensor([2549], device='cuda:0')
tensor(2549, device='cuda:0')
9375 13620
tensor(9374, device='cuda:0')

Epoch 1:  90%|█████████ | 36/40 [00:32<00:03,  1.10it/s, loss=0.904, v_num=161]2
tensor([2362], device='cuda:0')
tensor(2362, device='cuda:0')
6767 9943
tensor(6766, device='cuda:0')

Epoch 2:  50%|█████     | 20/40 [00:26<00:26,  1.32s/it, loss=0.866, v_num=161]
Validating: 0it [00:00, ?it/s]
Epoch 2:  90%|█████████ | 36/40 [00:32<00:03,  1.10it/s, loss=0.866, v_num=161]2
tensor([2302], device='cuda:0')

1

In [17]:
test_results = trainer.test(ckpt_path=None)
print(test_results)

Set SLURM handle signals.


Testing: 100%|██████████| 20/20 [00:08<00:00,  2.36it/s]
--------------------------------------------------------------------------------
DATALOADER:0 TEST RESULTS
{'current_lr': 0.004799999762326479,
 'eff': 0.6922658199138126,
 'loss': 0.8148619532585144,
 'ratio': 0.34052341805566033,
 'truth': array([0., 1., 0., ..., 0., 1., 1.], dtype=float32),
 'val_loss': 0.809785783290863}
--------------------------------------------------------------------------------
[{'loss': 0.8148619532585144, 'eff': 0.6922658199138126, 'truth': array([0., 1., 0., ..., 0., 1., 1.], dtype=float32), 'ratio': 0.34052341805566033, 'val_loss': 0.809785783290863, 'current_lr': 0.004799999762326479}]


In [8]:
os.environ['TENSORBOARD_BINARY'] = "/global/homes/j/jferguso/.conda/envs/exatrkx-tracking/bin/tensorboard"
%tensorboard --logdir tb_ecgnn_logs/ --port 0
nersc_tensorboard_helper.tb_address()
